### ISSUE TITLE
key issues

### ISSUE THREAD

**Issue by paul-eeoc** [DDoSolitary/yasfw#2] opened 2020-05-31 18:34 UTC
with this windows command:
`sftp myuser@mylocalserver`
it will ask for my password and I connect.   Based on this, I tried the following:
`yasfw --mount-point e --server mylocalserver --user myuser`
and it asks for my password.   it says:
`{ error_type: Request Denied, error_msg: "SFTP server: Permission denied", sftp_error_code: Some(PermissionDenied) }`

I tried using the mylocalserver IP address instead, and I also tried with elevated (admin) rights, but nothing worked.  According to yasfw, I am using dokan driver 400 dokan version 131.
My local server is a synology machine.   if SFTP works, why wouldn't yasfw work?

**Comment by DDoSolitary** [comment] 2020-06-01 04:54
Hello, could you please run the command with `-l Trace` and upload the full log so that I can find out what's going wrong? Thanks.

**Comment by paul-eeoc** [comment] 2020-06-01 11:53
I can successfully login and it makes a drive letter `E:`
But I cannot see folders or anything else.  I attach the log file.
[log.out.txt](https://github.com/DDoSolitary/yasfw/files/4711091/log.out.txt)

**Comment by DDoSolitary** [comment] 2020-06-01 13:44
It seems that the program is unable to read the root directory `/`. Could you please check if "myuser" has read access to `/`?

**Comment by paul-eeoc** [comment] 2020-06-02 11:51
It's a NAS from synology; it is linux/unix based.  I doubt that it uses ChrootDirectory.  
Here are the permissions:
```
$ ls -ld /
drwxr-xr-x 23 root root 4096 May 30 09:04 /
$
```
I can change permissions, just to see if it works.  What are the permission changes that I have to make? If it works, that's great but I will probably change the permissions back afterwards -- I am pretty sure the permissions are set the way they are for a reason.

I _could_ follow the instructions at this link below to make it key-based authentication instead of password-based authentication.  But I don't think it is an authentication issue. 
https://blog.aaronlenoir.com/2018/05/06/ssh-into-synology-nas-with-ssh-key/   
Not only that this link is a little old.

how is yasfw different from sftp?  Once I know the difference, perhaps I can tweak a setting in the NAS.

**Comment by DDoSolitary** [comment] 2020-06-06 04:20
Then this is pretty strange because the permission setting doesn't seems to have any problems. I theory yasfw doesn't have much difference compared to sftp except that they use different implementation of the SSH and SFTP protocol (sftp uses OpenSSH, yasfw uses libssh)

**Comment by DDoSolitary** [comment] 2021-05-29 14:24
I just did some tests on my friend's Synology NAS and successfully reproduced the error.

It seems that yasfw is making FXP_OPEN requests on directories, which isn't standard conformant (only FXP_OPENDIR is allowed) but is supported by openssh. Synology is using their own implementation and doesn't support this non-standard behavior.

Currently the handle returned by FXP_OPEN is used to query file/directory attributes, without this I'll have to list the parent directory of the target file, which is slower and will take some time to implement.

**Comment by DDoSolitary** [comment] 2021-05-30 10:18
Fix released in v0.1.1

**Closed by DDoSolitary** 2021-05-30 10:18 UTC

**Comment by paul-eeoc** [comment] 2021-06-01 11:49
Hey thanks for looking into this! Alas, I wouldn't have time to try this out until later this year (I am out of the country).

**Comment by resistancelion** [comment] 2021-08-28 14:15
> Hey thanks for looking into this! Alas, I wouldn't have time to try this out until later this year (I am out of the country).

Works well will opepSSH now

**Comment by paul-eeoc** [comment] 2021-10-23 14:35
Sorry that I never got back to you but it works great with my synology server! thanks!
